version: '3.8'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://contatinhouser:ultramegasecret@postgres:5432/contatinho
      NODE_ENV: development
      PORT: 3000
    ports:
      - '3000:3000'

  postgres:
    image: postgres:15.4
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: contatinhouser
      POSTGRES_PASSWORD: ultramegasecret
      POSTGRES_DB: contatinho
